spring:
  application:
    name: springboot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/roudblog?serverTimezone=GMT%2B8
    username: root
    password: 12345678
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2
    timeout: 5000

server:
  port: 8989

mybatis-plus:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: top.roud.cms.entity

logging:
  config: 'classpath:logback-spring.xml'

