spring:
  application:
    name: springboot
  data:
    mongodb:
      uri: mongodb://8.134.71.114:27017/roudblog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://8.134.71.114:3306/roudblog?serverTimezone=GMT%2B8
    username: root
    password: 12345671
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 8.134.71.114
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2
    timeout: 5000