spring:
  application:
    name: roudblog-cms
server:
  port: 8989
  tomcat:
    remoteip:
      remote-ip-header: 'x-forwarded-for'
      protocol-header: 'x-forwarded-proto'


mybatis-plus:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: top.roud.cms.entity.*
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false

# actuator 监控配置
management:
  endpoints:
    web:
      exposure:
        #默认值访问health,info端点  用*可以包含全部端点
        #include: "*"
        include: "health,info"
      #修改访问路径 2.0之前默认是/; 2.0默认是/actuator可以通过这个属性值修改
      base-path: /actuator
  endpoint:
    health:
      #设置health节点显示详细信息，默认不显示详细信息
      show-details: always #获得健康检查中所有指标的详细信息

logging:
  #控制台打印SQL语句
  level:
    com.lucifer.springboot.cache.mapper: debug
  #指定日志配置文件路径
  config: 'classpath:logback-spring.xml'

swagger:
  basic:
    enable: true
    username: roud
    password: 12345671

token:
  inner:
    expiredtime: 3
    secret: "roud;@a^m*art%$hur&blog"


roudblog:
  cache:
    save:
      days: 3